version: '3.4'
services:
    db:
        image: mariadb:latest
        container_name: db
        restart: always
        ports:
            - "3366:3306"
        expose:
            - 3306
        environment:
           MYSQL_ROOT_PASSWORD: 'test'
           
        volumes:
            - ./data:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql
    api:
        build: .
        container_name: api
        restart: always
        ports:
            - "80:5012" 
        depends_on: 
            - db 

        links:
            - db
        
volumes:
  db_data: